spring:
  datasource:
    url: jdbc:mysql://rm-bp1ig8i376x410it2o.mysql.rds.aliyuncs.com:3306/paascloud_mdc?characterEncoding=utf8&useSSL=false
    username: mmmdev
    password: Dev@2016
paascloud:
  aliyun:
    rocketMq:
      instanceName: paascloud-provider-mdc
      consumerGroup: CID_MDC
      producerGroup: PID_MDC
